# Generated by Django 2.1.5 on 2019-01-27 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='Full Name')),
                ('street', models.TextField(verbose_name='Street Address')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=30, verbose_name='State')),
                ('code', models.CharField(max_length=10, verbose_name='Pincode')),
                ('contact1', models.CharField(blank=True, max_length=15, verbose_name='Contact Number 1')),
                ('contact2', models.CharField(blank=True, max_length=15, verbose_name='Contact Number 2 (Optional)')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('PayTM', 'PayTM'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Cheque', 'Cheque'), ('Demand Draft', 'Demand Draft'), ('Free', 'Free')], max_length=20, verbose_name='Payment Method')),
                ('refId', models.CharField(blank=True, max_length=80, verbose_name='Reference ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Payment Amount')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('renewDate', models.DateField(default=django.utils.timezone.now, verbose_name='Last Renew Date')),
                ('period', models.PositiveIntegerField(choices=[(24, 'Two Years'), (60, 'Five Months'), (120, 'Ten Years'), (240, 'Twenty Years'), (0, 'Lifetime')], default=12, verbose_name='Period')),
                ('expireDate', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('active', models.BooleanField(default=True, verbose_name='Is Subscription Active?')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Label')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Subscription')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='portal.Subscription'),
        ),
        migrations.AddField(
            model_name='address',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='portal.Subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionlabel',
            unique_together={('subscription', 'label')},
        ),
    ]
